apply plugin: 'com.android.application'

android {
    namespace 'com.nrn.alpha6'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nrn.alpha6'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation project(':capacitor-android')
}
